name: Contentful Webhook

on:
  repository_dispatch:
    types: [contentful_event]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Event Data
        run: echo "Received Contentful webhook event: ${{ toJson(github.event) }}"
